apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  JWT_SECRET: "f468468cb80df37d0de5096e8f130519e8d60296f1b56448de012db650de94c7"
  STRIPE_SECRET_KEY: "PLACEHOLDER_KEY_DO_NOT_COMMIT"
